# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/wconnell/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Users/wconnell/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wconnell/x/ft_ls

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wconnell/x/ft_ls

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/wconnell/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Users/wconnell/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wconnell/x/ft_ls/CMakeFiles /Users/wconnell/x/ft_ls/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wconnell/x/ft_ls/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ft_ls

# Build rule for target.
ft_ls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ft_ls
.PHONY : ft_ls

# fast build rule for target.
ft_ls/fast:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/build
.PHONY : ft_ls/fast

#=============================================================================
# Target rules for targets named libft

# Build rule for target.
libft: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libft
.PHONY : libft

# fast build rule for target.
libft/fast:
	$(MAKE) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/build
.PHONY : libft/fast

bust.o: bust.c.o

.PHONY : bust.o

# target to build an object file
bust.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/bust.c.o
.PHONY : bust.c.o

bust.i: bust.c.i

.PHONY : bust.i

# target to preprocess a source file
bust.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/bust.c.i
.PHONY : bust.c.i

bust.s: bust.c.s

.PHONY : bust.s

# target to generate assembly for a file
bust.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/bust.c.s
.PHONY : bust.c.s

flags.o: flags.c.o

.PHONY : flags.o

# target to build an object file
flags.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/flags.c.o
.PHONY : flags.c.o

flags.i: flags.c.i

.PHONY : flags.i

# target to preprocess a source file
flags.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/flags.c.i
.PHONY : flags.c.i

flags.s: flags.c.s

.PHONY : flags.s

# target to generate assembly for a file
flags.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/flags.c.s
.PHONY : flags.c.s

free_func.o: free_func.c.o

.PHONY : free_func.o

# target to build an object file
free_func.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/free_func.c.o
.PHONY : free_func.c.o

free_func.i: free_func.c.i

.PHONY : free_func.i

# target to preprocess a source file
free_func.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/free_func.c.i
.PHONY : free_func.c.i

free_func.s: free_func.c.s

.PHONY : free_func.s

# target to generate assembly for a file
free_func.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/free_func.c.s
.PHONY : free_func.c.s

ft_ls.o: ft_ls.c.o

.PHONY : ft_ls.o

# target to build an object file
ft_ls.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/ft_ls.c.o
.PHONY : ft_ls.c.o

ft_ls.i: ft_ls.c.i

.PHONY : ft_ls.i

# target to preprocess a source file
ft_ls.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/ft_ls.c.i
.PHONY : ft_ls.c.i

ft_ls.s: ft_ls.c.s

.PHONY : ft_ls.s

# target to generate assembly for a file
ft_ls.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/ft_ls.c.s
.PHONY : ft_ls.c.s

init.o: init.c.o

.PHONY : init.o

# target to build an object file
init.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/init.c.o
.PHONY : init.c.o

init.i: init.c.i

.PHONY : init.i

# target to preprocess a source file
init.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/init.c.i
.PHONY : init.c.i

init.s: init.c.s

.PHONY : init.s

# target to generate assembly for a file
init.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/init.c.s
.PHONY : init.c.s

print.o: print.c.o

.PHONY : print.o

# target to build an object file
print.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/print.c.o
.PHONY : print.c.o

print.i: print.c.i

.PHONY : print.i

# target to preprocess a source file
print.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/print.c.i
.PHONY : print.c.i

print.s: print.c.s

.PHONY : print.s

# target to generate assembly for a file
print.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/print.c.s
.PHONY : print.c.s

print_l.o: print_l.c.o

.PHONY : print_l.o

# target to build an object file
print_l.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/print_l.c.o
.PHONY : print_l.c.o

print_l.i: print_l.c.i

.PHONY : print_l.i

# target to preprocess a source file
print_l.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/print_l.c.i
.PHONY : print_l.c.i

print_l.s: print_l.c.s

.PHONY : print_l.s

# target to generate assembly for a file
print_l.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/print_l.c.s
.PHONY : print_l.c.s

print_total.o: print_total.c.o

.PHONY : print_total.o

# target to build an object file
print_total.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/print_total.c.o
.PHONY : print_total.c.o

print_total.i: print_total.c.i

.PHONY : print_total.i

# target to preprocess a source file
print_total.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/print_total.c.i
.PHONY : print_total.c.i

print_total.s: print_total.c.s

.PHONY : print_total.s

# target to generate assembly for a file
print_total.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/print_total.c.s
.PHONY : print_total.c.s

push_back.o: push_back.c.o

.PHONY : push_back.o

# target to build an object file
push_back.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/push_back.c.o
.PHONY : push_back.c.o

push_back.i: push_back.c.i

.PHONY : push_back.i

# target to preprocess a source file
push_back.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/push_back.c.i
.PHONY : push_back.c.i

push_back.s: push_back.c.s

.PHONY : push_back.s

# target to generate assembly for a file
push_back.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/push_back.c.s
.PHONY : push_back.c.s

rec_penetration.o: rec_penetration.c.o

.PHONY : rec_penetration.o

# target to build an object file
rec_penetration.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/rec_penetration.c.o
.PHONY : rec_penetration.c.o

rec_penetration.i: rec_penetration.c.i

.PHONY : rec_penetration.i

# target to preprocess a source file
rec_penetration.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/rec_penetration.c.i
.PHONY : rec_penetration.c.i

rec_penetration.s: rec_penetration.c.s

.PHONY : rec_penetration.s

# target to generate assembly for a file
rec_penetration.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/rec_penetration.c.s
.PHONY : rec_penetration.c.s

struct_filenames.o: struct_filenames.c.o

.PHONY : struct_filenames.o

# target to build an object file
struct_filenames.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/struct_filenames.c.o
.PHONY : struct_filenames.c.o

struct_filenames.i: struct_filenames.c.i

.PHONY : struct_filenames.i

# target to preprocess a source file
struct_filenames.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/struct_filenames.c.i
.PHONY : struct_filenames.c.i

struct_filenames.s: struct_filenames.c.s

.PHONY : struct_filenames.s

# target to generate assembly for a file
struct_filenames.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/struct_filenames.c.s
.PHONY : struct_filenames.c.s

struct_sort.o: struct_sort.c.o

.PHONY : struct_sort.o

# target to build an object file
struct_sort.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/struct_sort.c.o
.PHONY : struct_sort.c.o

struct_sort.i: struct_sort.c.i

.PHONY : struct_sort.i

# target to preprocess a source file
struct_sort.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/struct_sort.c.i
.PHONY : struct_sort.c.i

struct_sort.s: struct_sort.c.s

.PHONY : struct_sort.s

# target to generate assembly for a file
struct_sort.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/struct_sort.c.s
.PHONY : struct_sort.c.s

whatsspecific.o: whatsspecific.c.o

.PHONY : whatsspecific.o

# target to build an object file
whatsspecific.c.o:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/whatsspecific.c.o
.PHONY : whatsspecific.c.o

whatsspecific.i: whatsspecific.c.i

.PHONY : whatsspecific.i

# target to preprocess a source file
whatsspecific.c.i:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/whatsspecific.c.i
.PHONY : whatsspecific.c.i

whatsspecific.s: whatsspecific.c.s

.PHONY : whatsspecific.s

# target to generate assembly for a file
whatsspecific.c.s:
	$(MAKE) -f CMakeFiles/ft_ls.dir/build.make CMakeFiles/ft_ls.dir/whatsspecific.c.s
.PHONY : whatsspecific.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ft_ls"
	@echo "... libft"
	@echo "... bust.o"
	@echo "... bust.i"
	@echo "... bust.s"
	@echo "... flags.o"
	@echo "... flags.i"
	@echo "... flags.s"
	@echo "... free_func.o"
	@echo "... free_func.i"
	@echo "... free_func.s"
	@echo "... ft_ls.o"
	@echo "... ft_ls.i"
	@echo "... ft_ls.s"
	@echo "... init.o"
	@echo "... init.i"
	@echo "... init.s"
	@echo "... print.o"
	@echo "... print.i"
	@echo "... print.s"
	@echo "... print_l.o"
	@echo "... print_l.i"
	@echo "... print_l.s"
	@echo "... print_total.o"
	@echo "... print_total.i"
	@echo "... print_total.s"
	@echo "... push_back.o"
	@echo "... push_back.i"
	@echo "... push_back.s"
	@echo "... rec_penetration.o"
	@echo "... rec_penetration.i"
	@echo "... rec_penetration.s"
	@echo "... struct_filenames.o"
	@echo "... struct_filenames.i"
	@echo "... struct_filenames.s"
	@echo "... struct_sort.o"
	@echo "... struct_sort.i"
	@echo "... struct_sort.s"
	@echo "... whatsspecific.o"
	@echo "... whatsspecific.i"
	@echo "... whatsspecific.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

